print()
print("Задание №1")
print()
print("Как вас зовут: ")
name1 = input()
print("Какая ваша суперсила: ")
name2 = input()
print("Сколько вам лет: ")
name3 = input()
print("Какой цвет у вашего костюма: ")
name4 = input()
print("Какой у вас псевдоним: ")
name5 = input()
print("Вы супергерой или суперзлодей: ")
name6 = input()
print("--------")
print( "Имя: " + name1   )
print("--------")
print( "Суперсила: " + name2   )
print("--------")
print( "Вам: " + name3 + " лет"   )
print("--------")
print( "Цвет костюма: " + name4   )
print("--------")
print( "Псевдоним: " + name5   )
print("--------")
print( "Вы: " + name6   )
print("--------")
print()
print("Задание №2")
print()
print("Одна конфета стоит 12р")
print("В одном пакете 5 конфет")
print("Вес 1 конфеты 25гр")
num1 = input("Конфет: ")
num_float = float(num1)

print("Вы выбрали " + num1)
print(f"{round(num_float * 25)} - грамм")
print(f"{round(num_float * 12)} - рублей")
print(f"{int(num_float / 5)} - пакет/а/ов")